user_lobyenattente:
    path:   /Lobbyneedtocomplet
    defaults: { _controller: challengeUserBundle:Lobby:index }

user_lobby_acheter:
    path:   /Lobbybought
    defaults: { _controller: challengeUserBundle:Lobby:lobbybuy }