challenge_payment:
    resource: "@challengePaymentBundle/Resources/config/routing.yml"
    prefix:   /payment

challenge_news:
    resource: "@challengeNewsBundle/Resources/config/routing.yml"
    prefix:   /news

challenge_user:
    resource: "@challengeUserBundle/Resources/config/routing.yml"
    prefix:   /

challenge_l:
    resource: "@challengeLBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /user

payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"

payum_authorize:
    resource: "@PayumBundle/Resources/config/routing/authorize.xml"

payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"