# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:
    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }

services:
    admin.lobby:
        class: challengePaymentBundle\Admin\LobbyAdmin
        arguments: [~, challengePaymentBundle\Entity\Lobby, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Lobby }