<?php

namespace challenge\PaymentBundle\Entity;

/**
 * FormuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormuleRepository extends \Doctrine\ORM\EntityRepository
{
}
