<?php

namespace challenge\PaymentBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;


/**
 * FormuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormuleRepository extends EntityRepository
{
    public function getformule(){


        $query=$this->createQueryBuilder('f')
                    ->leftJoin('f.game','g')
                    ->leftJoin('f.lobby','l')
                    ->addSelect('g')
                    ->addSelect('l')
                    ->getQuery();


        return $query->getResult();
    }

}
