<?php

namespace challenge\PaymentBundle\Entity;

/**
 * LobbyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LobbyRepository extends \Doctrine\ORM\EntityRepository
{
}
